# Generated by Django 2.0.4 on 2018-08-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_freelancer',
            field=models.BooleanField(default=False, verbose_name='freelancer status'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('freelancer', 'freelancer'), ('employer', 'employer'), ('choose one', 'choose one')], default='null', max_length=50),
            preserve_default=False,
        ),
    ]
