# Generated by Django 2.0.4 on 2018-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20180817_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('freelancer', 'freelancer'), ('employer', 'employer')], max_length=50),
        ),
    ]
