# Generated by Django 2.0.4 on 2018-08-18 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20180817_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_freelancer',
        ),
    ]
