# Generated by Django 2.0.4 on 2018-08-21 00:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=50, null=True, verbose_name='post name')),
                ('post_type', models.CharField(choices=[('for pay', 'for pay'), ('volunteer', 'volunteer')], default='for pay', max_length=50, verbose_name='post type')),
                ('post_start_date', models.DateField(default=datetime.datetime.now, verbose_name='start date')),
                ('post_end_date', models.DateField(default=datetime.datetime.now, verbose_name='end date')),
                ('post_details', models.TextField(verbose_name='post details')),
                ('experience_description', models.TextField(verbose_name='experience description')),
                ('work_location', models.CharField(choices=[('from your home', 'from your home'), ('at the office', 'at the office')], default='for profit', max_length=50, verbose_name='work location')),
                ('date_posted', models.DateField()),
                ('candidate_accepted', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=50, verbose_name='have you accpeted a candidate')),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
