# Generated by Django 2.0.4 on 2018-08-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='post_name',
            field=models.CharField(default='null', max_length=50, verbose_name='post name'),
            preserve_default=False,
        ),
    ]
