# Generated by Django 2.0.4 on 2018-08-14 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2018, 8, 14, 6, 50, 47, 184056), verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=254, verbose_name='email'),
        ),
    ]
