# Generated by Django 2.0.4 on 2018-08-15 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180814_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(upload_to='profile_image'),
        ),
    ]
