# Generated by Django 2.0.4 on 2018-08-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180815_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='phone number'),
        ),
    ]
