# Generated by Django 2.0.4 on 2018-08-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20180815_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_description',
            field=models.TextField(default='null', verbose_name='description of experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mission_statement',
            field=models.TextField(default='null', verbose_name='mission statement'),
            preserve_default=False,
        ),
    ]
