# Generated by Django 2.0.4 on 2018-08-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20180815_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_length',
            field=models.CharField(choices=[('0-5', '0-5'), ('5-10', '5-10'), ('10-15', '10-15'), ('15-20', '15-20'), ('20-25', '20-25'), ('25-30', '25-30'), ('30 or more', '30 or more')], default='0-5', max_length=10, verbose_name='years of work experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='opportunity_type',
            field=models.CharField(choices=[('freelancing', 'freelancing'), ('volunteering', 'volunteering'), ('both', 'both')], default='freelancing', max_length=50, verbose_name='opportunity type'),
        ),
    ]
