# Generated by Django 2.0.4 on 2018-08-17 00:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0006_auto_20180816_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='previous employer')),
                ('position', models.CharField(max_length=100, verbose_name='previous employer')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='start date')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='end date')),
                ('experience_description', models.TextField(verbose_name='experience_description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=50, verbose_name='rating')),
                ('rating_description', models.TextField(verbose_name='rating description')),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_rating_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_being_rated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
