# Generated by Django 2.0.4 on 2018-08-17 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0007_experience_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_description',
            field=models.TextField(verbose_name='experience description'),
        ),
    ]
