# Generated by Django 2.0.4 on 2018-08-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20180816_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience_length',
            field=models.CharField(choices=[('0-5', '0-5'), ('6-10', '6-10'), ('11-15', '11-15'), ('16-20', '16-20'), ('21-25', '21-25'), ('26-30', '26-30'), ('31 or more', '31 or more')], default='0-5', max_length=10, verbose_name='years of work experience'),
        ),
    ]
