# Generated by Django 2.0.4 on 2018-08-17 03:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0009_auto_20180816_2106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experience',
            new_name='UserExperience',
        ),
        migrations.RenameModel(
            old_name='Rating',
            new_name='UserRating',
        ),
    ]
